# .github/workflows/ci.yml
name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Verify Node.js version
      run: node -v

    - name: Fix permissions for jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Run tests
      run: npm test

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verify JDK version
      run: java -version

    - name: Install SonarScanner CLI
      run: npm install -g sonar-scanner

    - name: Run SonarCloud Scan with retries
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        for i in {1..3}; do
          sonar-scanner -X && break || sleep 30;
        done

    - name: Wait for SonarCloud processing
      run: sleep 60

    - name: SonarCloud Quality Gate
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=jonathan-beskow_integracao-continua")
        echo "API Response: $RESPONSE"
        STATUS=$(echo $RESPONSE | jq -r .projectStatus.status)
        if [ "$STATUS" != "OK" ]; then
          echo "Quality gate failed: $STATUS"
          exit 1
        else
          echo "Quality gate passed: $STATUS"
        fi
